[ADDED] Navbar
COPS-IITBHU/Study-Portal pull request #11
Opened 2022-12-14 12:16 UTC by atulyadav745

Responsive Navbar is added
Fixed issue #1

2022-12-14 15:35 UTC, king-11 requested changes
Combine into a single component and use semantic html instead of just div

2022-12-14 15:35 UTC, king-11 commented on components/Navbar/NavLinks.tsx
> +			{links.map((Link,i) => (
Use a ul tag and flex box

2022-12-14 15:35 UTC, king-11 commented on components/Navbar/NavLinks.tsx
> +						<h1 className='py-7'>{Link.name}</h1>
Don't use h1 prefer span or p

2022-12-14 15:35 UTC, king-11 commented on components/Navbar/Login.tsx
> +    <div>
Don't make this a component directly embed a button in navbar.tsx without div wrapper

2022-12-14 15:35 UTC, king-11 commented on components/Navbar/Navbar.tsx
> +          <NavLinks />
Embed links here directly instead of a separate component

2022-12-14 17:21 UTC, atulyadav745 commented
@king-11 Thanks Bhaiya. Great Review, hope I fixed it.
![Screenshot (274)](https://user-images.githubusercontent.com/106299466/207663794-2a5323cc-1cfb-4489-b6dc-d48a51ee4404.png)

![Screenshot (275)](https://user-images.githubusercontent.com/106299466/207663459-33d1d725-451f-4bd5-b54e-4920ed507a9e.png)
ng)
![Screenshot (276)](https://user-images.githubusercontent.com/106299466/207663473-77f83525-c13a-4c65-b678-5e5a1a146442.png)

2022-12-21 10:56 UTC, merged

2022-12-21 15:43 UTC, king-11 commented
@Divyansh013 we can use the new layout feature maybe configure that